doc_source/create-kubeconfig.md

Closes #1 
Added a note on how to set aws profile in kubeconfig file.

added note regarding multiple profiles

---

doc_source/getting-started.md

Make the paragraph more readable

---

doc_source/cni-custom-network.md

CNI Custom Networking: Fix typo in ENIConfig.yaml

---

doc_source/getting-started.md

No isse
Fixing missing instruction: adding tags step as it is missing in the creating role section of the getting stated guide of EKS

Adding tags step as it is missing

---

doc_source/cni-upgrades.md

Update latest CNI version to 1.4.1 in cni-upgrades.md

Update latest CNI version to 1.4.1

---

doc_source/install-kubectl.md

**Relates to:** https://github.com/aws/containers-roadmap/issues/30
Updates kubectl 1.13 from amazon-eks s3.
https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html

Updates kubectl 1.13 documentation from amazon-eks

---

doc_source/worker_node_IAM_role.md

Fix typos in the worker node iam docs

---

doc_source/getting-started-eksctl.md

Add region to create cluster command to show this parameter

Updated region parameter

---

doc_source/arm-support.md

Fixed broken links to the ARM support preview repository
Fixed broken links to the ARM support preview repository

Fix broken links to ARM Support Preview repo

---

doc_source/fsx-csi.md

N/A
Add Deployment Type support for Amazon FSx for Lustre CSI Driver v0.3

Add Deployment Type support for Amazon FSx for Lustre CSI Driver v0.3

---

doc_source/fsx-csi.md

Fix fsx-csi driver installation command, since the url should be surrounded in quotes

Fix fsx-csi driver installation command

---

doc_source/troubleshooting.md

Updated troubleshooting doc to point to latest EKS log collector script which now is in EKS AMI GitHub repository. 
Ref: https://github.com/aws/amazon-vpc-cni-k8s/pull/864/

Updated troubleshooting.md

---

doc_source/fargate-pod-configuration.md

Update fargate-pod-configuration.md to reflect updated Fargate storage value

---

doc_source/fargate.md

Update guidance on using secondary CIDR block for Fargate pods

Using secondary CIDR block with Fargate

---

doc_source/eks-using-tags.md

Update tag information for Fargate Profiles using wording from CLI docs (--tags)
https://docs.aws.amazon.com/cli/latest/reference/eks/create-fargate-profile.html
Add basic tag support and propagation information for EKS Fargate profiles using wording from the API/CLI documentation
https://docs.aws.amazon.com/cli/latest/reference/eks/create-fargate-profile.html

Update tagging information for Fargate Profiles

---

doc_source/cni-custom-network.md

Fixed grammar in maxPods calculation

---

doc_source/update-cluster.md

`update cluster` has been renamed to upgrade cluster` with [0.22](https://github.com/weaveworks/eksctl/releases/tag/0.22.0).

Adjust eksctl update command

---

doc_source/service-quotas.md

Fixed syntax for list-aws-default-service-quotas CLI

---

doc_source/update-cluster.md

Address https://github.com/awsdocs/amazon-eks-user-guide/pull/131.

doc_source: add kube-proxy update notes

---

doc_source/ebs-csi.md

**Description of changes:**
Updated the docs to recommended the newest version.

Bump recommended version to 0.5.0 on ebs-csi.md

---

doc_source/launch-templates.md

Updating information around kubelet customization with launch templates

Add note about kubelet customization

---

doc_source/security-groups-for-pods.md

Clarify Source NAT consideration

---

doc_source/create-managed-node-group.md

Note about instance types for console

---

doc_source/eks-optimized-ami.md

Update `NVIDIA end user license agreement` link to redirect to https://www.nvidia.com/en-us/drivers/nvidia-license/.

Update NVIDIA license agreement link

---

doc_source/security.md

N/A
Added note about host-level resources

Added note about host resources

---

doc_source/iam-roles-for-service-accounts-technical-overview.md

Update info about region variable with IRSA

---

doc_source/ebs-csi.md

Update CSI driver to add tags to dynamically provisioned ebs volumes

---

doc_source/kubernetes-versions.md

Add 1.18 launch date

---

doc_source/launch-node-bottlerocket.md

You can deploy Bottlerocket on managed node groups using a custom AMI

Remove note about managed nodes

---

doc_source/view-workloads.md

Modify the first prerequisites that might misleading customer as currently only mention IAM user can view workload.

Update View Workload Prerequisites

---

doc_source/kubernetes-versions.md

*Fix typo in kubernetes-version.md file.*

fix typo in doc_source/kubernetes-versions.md

---

doc_source/kubernetes-versions.md

Add note on managed node groups

---

doc_source/create-node-role.md

Cosmetic fix only to unify the style of the policy name.

Uniformize format for policy name

---

doc_source/efs-csi.md

Revert PR #277 , I went back to confirm the original link works in kustomization behavior, which is not BROKEN. 

Revert PR #277

---

doc_source/add-user-role.md

Description of changes:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice

Fix typo ClusterRoleBinding

---

doc_source/kubernetes-versions.md

*Issue #, if available:* NA
*Description of changes:* It seems that the documentation structure has changed leaving a few links unreachable. This PR fixes those links.
Note: I haven't checked all the links on the page.

Fix broken links

---

doc_source/cni-custom-network.md

*Description of changes:* `Creating a subnet in your VPC` link redirects to somewhere else, this PR will fix this.

fix broken link

---

doc_source/eks-optimized-ami.md

Update GPU device plugin

---

doc_source/aws-load-balancer-controller.md

Fixes typo in documentation for AWS load balancer controller

Fix typo in AWS load balancer controller file name

---

doc_source/authenticate-oidc-identity-provider.md

Add self signed cert support note

---

doc_source/create-node-role.md

between AWS Management and Console AWS CloudFormation, understanding that these are two alternative tools to create roles.

Grammar: added "or"

---

doc_source/alb-ingress.md
doc_source/aws-load-balancer-controller.md
doc_source/load-balancing.md

Documentation updates for aws load balancer controller v2.2.0

docs update for aws load balancer controller v2.2.0

---

doc_source/managing-vpc-cni.md

**Description of changes:**
Updates to the VPC CNI manual update instructions (https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on)
- fixed CNI YAML address
- updated to latest version (v1.7.10)

VPC CNI YAML URL CORRECTION

---

doc_source/aws-load-balancer-controller.md

v2_2_0_full.yaml file has been changes hence the Replace `your-cluster-name` should be line number 788 not 797.

change the correct line number to replace the cluster name

---

doc_source/efs-csi.md

The urls are pointing to driver 1.2.  Via this commit;  the document will point to driver 1.3
No issue id available.  

Update README to refer to driver 1.3

---

doc_source/managing-kube-proxy.md

This PR fixes three spelling mistakes in the documentation.

Fix spelling mistakes

---

doc_source/managing-coredns.md

Just changed the 'line' to 'block' since it is missleading and can lead to confusion what to add.

Updated mentioning for permissions.

---

doc_source/ebs-csi.md

Update ebs csi driver install instructions to point to ecr public image

update ebs csi driver install instructions

---

doc_source/fargate-logging.md

Signed-off-by: Michael Hausenblas <hausenbl@amazon.com>
This PR addresses Fargate logging:
1. It makes the configuration more prominent by pulling the allowed `ConfigMap` values to the beginning
2. It  shows the actual AES config settings (not just generic ES ones) and adds the necessary access control settings
3. Improves the overall flow and directions.

addresses Fargate logging docs

---

doc_source/network_reqs.md

Fixed known issue about additional CIDR blocks

---

doc_source/eks-optimized-ami.md

*Issue #423*
*- omit dollar symbol on overrideBootstrapCommand*

Update Amazon EKS optimized Amazon Linux AMIs docs

---

doc_source/fargate-profile.md

Updating the cli command to delete fargate profile via cli

update aws cli for fargate profile deletion command

---

doc_source/install-kubectl.md

Fix typo on kubectl on Linux - Kubernetes 1.21

---

doc_source/install-kubectl.md

update curl location for linux

---

doc_source/install-kubectl.md

Missing download filename in curl command for 1.20 (Linux)

---

doc_source/update-cluster.md

update nvidia k8s-device-plugin version

update nvidia k8s-device-plugin version

---

doc_source/managing-coredns.md

1.8.4 is the default with v1.21

update coredns version

---

doc_source/fargate-pod-configuration.md

Modification of fargate-pod-config to include requests and limits section for Fargate pods.

Added requests and limits secton for EKS Fargate

---

doc_source/alternate-cni-plugins.md

Change to pointing to the latest version.

Fix Antrea installation document link

---

doc_source/managing-coredns.md

By reading this documentation, it's easy to be confused by the word "line" and understand like "add exactly one line from the following block of yaml".

update the wording to be less confusing

---

doc_source/add-user-role.md

typo in the get clusterrolebindings command on line 50. Corrected it

updated the clusterrolebindings  typo in this page

---

doc_source/managed-node-update-behavior.md

Explaining force flag behavior in managed nodes update process. Please let me know if any changes are needed.

Force flag behavior with Managed Nodes update process

---

doc_source/windows-support.md

Internal ticket
Added M6a.x as instance not supported for Windows workloads.

Update windows support docs for instances suppported

---

doc_source/kubernetes-versions.md

Extend some support dates

---

doc_source/network_reqs.md

- AWSAWS -> AWS
*Description of changes:* `AWSAWS` -> `AWS`

Fix typo; add newline to end of file

---

doc_source/cni-increase-ip-addresses.md

Fixes a type, change ekctl to eksctl

Fix typo for ekctl to eksctl

---

doc_source/kubernetes-versions.md

Adding a more concrete date for EKS v1.22 launch.

updated EKS v1.21 launch date

---

doc_source/pod-execution-role.md

Adding deputy controls to PodExecutionRole doc

Adding deputy controls to PodExecutionRole doc

---

doc_source/managing-ebs-csi-self-managed-add-on.md

The repository has change it's hierarchy, instead of specs is manifests

Change the folder where the kubectl apply works

---

doc_source/update-cluster.md

Remove confusing line that doesn't apply anymore

---

doc_source/create-cluster.md

Fix a typo / incomplete sentence.

Fix a typo / incomplete sentence.

---

doc_source/update-cluster.md

Typo in update-cluster.md

---

doc_source/service_IAM_role.md

*Issue #, if available:* 
*Description of changes:* Remove a duplicate that doesn't fit with the choice given by console.

Remove Duplicate EKS selections

---

doc_source/fsx-csi.md

Fix incorrect line break, change "/" to "\"
introduced by 994c8b60405a54f220c4dcb8b3e080161dacb2d5

Fix incorrect line break, change "/" to "\"

---

doc_source/cert-signing.md

Remove duplicate (and wrong) command

doc: Update cert-signing.md

---

doc_source/managing-vpc-cni.md

*Issue #, if available:* none
Moved empty code lines for better readability. Things that belong together are now closer together, things that don't are farther apart.

docs: improve readability by re-ordering lines

---

doc_source/cni-custom-network.md
doc_source/managing-vpc-cni.md

Update CNI Addon Version to the latest version.

Update CNI Addon Version.

---

doc_source/api-server-flags.md

typo
Obviously, there is a typo introduced by b463bbd034eb859ecea175d205455f7336073017.

Fix strange typo

---

doc_source/kubernetes-versions.md

Updating the EOS date for EKS v1.20

---

doc_source/managing-kube-proxy.md

* Update kube-proxy addon. Mention skew-policy
* Updated the addons versions to the latest which will be available from 18-July-2022
* Mention about kube-proxy version skew policy

Update kube-proxy addon. Mention skew-policy

---

doc_source/service-accounts.md

Added fluentd versions that refetches service account tokens.

---

doc_source/service-accounts.md

Added fluentd version that has the fix to refetch service account tokens 

---

doc_source/kubernetes-versions.md

EKS v1.24 timelines

---

doc_source/csi-iam-role.md

The annotation step was missing

Add ebs-csi-controller-sa service account annotation step

---

doc_source/opentelemetry.md

ADOT supports Arm now

---

doc_source/kubernetes-versions.md

n/a
remove 1.19 from "currently available" -- end of support was Aug 1. 

remove k8s v 1.19 from "currently available"

---

doc_source/aws-load-balancer-controller.md

n/a
add a related content note to the "install LBC" page. this may help users understand where to go to find answers. 
very open to feedback.

add related content note to load balancer page

---

doc_source/kubernetes-versions.md

*Description of changes:* Updating end of support date for 1.21

Update 1.21 end of support date

---

doc_source/enable-kms.md

Updating the yml name which is shared in instructions.
There's a snippet of example which shows creation of "cluster.yml" > However, in proceeding commands wrong file name has been supplied which is confusing for reader.
Changed the yaml file to correct as per snippet example.

Updating textual changes

---

doc_source/getting-started-eksctl.md

- n/a
- Sample command output is outdated, contains misleading information.

eksctl - sample command output should match actual state

---

doc_source/managing-vpc-cni.md

Update CNI addons version to latest supported version 1.12.0-eksbuild.1

update cni addons versions to 1.12.0

---

doc_source/eks-optimized-windows-ami.md
doc_source/managing-ebs-csi.md

Update Note for EBS CSI driver for Windows Server 2022

Update EBS CSI driver Note for Windows Server 2022

---

doc_source/troubleshooting-connector.md

*Issue #, if available:* n/a
*Description of changes:* Fix two obvious typos in `troubleshooting-connector.md`

Fix a couple of typos in troubleshooting-connector

---

doc_source/kubernetes-versions.md

Added EKS v1.25 release dates

---

doc_source/managing-kube-proxy.md

Update the latest available versions of kube-proxy add-ons for:
v1.23.13-minimal-eksbuild.2-> v1.23.15-minimal-eksbuild.1
v1.24.7-minimal-eksbuild.2 -> v1.24.9-minimal-eksbuild.1

update the latest available versions of kube-proxy add-ons

---

doc_source/retrieve-ami-id.md

There was an extra `.` in the text. I thought it was a speck of dirt on my monitor, but it moved when I scrolled. 😄 That's all for now!

Remove extra full stop

---

doc_source/managed-node-update-behavior.md

This should be reviewed by Ravi from the service team before merging.
Clarifies upgrade behavior to reflect service side changes

Clarifies upgrade behavior to reflect service side changes

---

doc_source/cost-monitoring.md

Customers told us that FAQ #1 does not provide a clear list of features available to them and not available to them through the AWS optimized Kubecost bundle. Updating the messaging to address that issue.

Updating FAQ#1

---

doc_source/alb-ingress.md
doc_source/aws-load-balancer-controller.md

Update the iam policy url reference to point to the content on release2.4 branch. 

 update eks docs for aws lbc v2.4.7 

---

doc_source/managing-kube-proxy.md

Update the latest available self-managed kube-proxy container image version for each Amazon EKS cluster version according to the new release addons.

update kube-proxy addons information

---

doc_source/install-kubectl.md

This change updates the install-kubelet.md with latest binaries for 1.22 through 1.25 as part of this MCM: https://mcm.amazon.com/cms/MCM-75454019

Update install-kublet.md with latest binaries

---

doc_source/update-cluster.md

Add detail about existing cluster resources installed by EKS

Add note about existing EKS installed resources

---

doc_source/eks-compute.md

MNG does support dedicated instances

---

doc_source/eksctl.md

Update installation instructions for eksctl corresponding to https://github.com/weaveworks/eksctl/pull/6376

Update installation instructions to remove third-party installers

---

doc_source/managing-coredns.md

Update the managing-coredns.md, adding ```v1.9.3-eksbuild.3``` as the latest version of EKS Managed addon. 

udpate managing-coredns.md

---

doc_source/vertical-pod-autoscaler.md

Fix typo in vertical-pod-autoscaler.md

---

doc_source/cni-custom-network.md

*Description of changes:* Looks like eni_config_label_def and eni_config_annotation_def got mixed up

Update cni-custom-network.md fix eni_config_annotation_def link

---

doc_source/coredns-autoscaling.md

Fix dashes in command argument flags
N/A
Fix formatting of arguments. Typos.

Update coredns-autoscaling.md fix argument dash typos

---

doc_source/lbc-manifest.md

serviceAccount configuration in v2_7_2_full.yaml has moved from lines 596-604 to 612-620

Update sed command in lbc-manifest.md

---

doc_source/cni-network-policy.md

The guide does not provide information on what exactly the user needs to do to successfully remove/disable network policies feature in VPC CNI. 
Added a section before the Kubernetes Network Policies part. 

Added Disabling Network Policies topic

---

doc_source/related-projects.md

Add Karpenter to related autoscaling projects docs

Add Karpenter to related autoscaling projects docs

---

doc_source/s3-csi.md

The page title currently is incorrect for Mountpoint S3's CSI Driver page. I have proposed this update though its a bit long, please feel free to adjust.

Fix Mountpoint S3 CSI Driver page title
