doc_source/network_reqs.md

*Description of changes:* For each cluster created Amazon EKS tags the VPC containing the subnets specified. This was not documented.

Amazon EKS adds VPC tags

---

doc_source/calico.md

No issue, but this is a takeover of #6 which @bcreane asked me to submit since he's out for the next 2 weeks.
Update the install procedure for new Calico clusters.
The previous manifest (v1.0.0) included both the Calico daemonset and a modified aws-node daemonset.
The new manifest includes a newer release of Calico that does not need to modify the underlying aws-node daemonset.
#6 was a bit more complicated because it tried to cover the update procedure from the previous manifest to the new manifest. I'd prefer we keep the install docs short and sweet, and if necessary, put upgrade instructions in a new doc. I'm open to doing so as part of this PR if maintainers can advise where that should go.
I'm also not sure if the new manifest needs …

Update calico install docs to use manifest which supports eni interfaces

---

doc_source/getting-started.md

The current document wording: NodeGroupName: Enter a name for your node group that is included in your Auto Scaling node group name. makes it sound like these resources should already exist. Changing the tense to reflect that this parameter will apply to resources which will be created by the template.

tensechange.md

---

doc_source/sec-group-reqs.md

Page has an incorrect ephemeral port range for inbound access to control plane stated.
Corrected the stated ephemeral port range for inbound access to control plane SG from the incorrect 66535 to correct 65535 (2^16-1). Hope it helps!

Correction to sec-group-reqs.md

---

doc_source/calico.md

To remove calico, we should remove all the resources from the manifest file, not just the calico daemonset

Fix the steps to delete calico

---

doc_source/external-snat.md

The environment variables for the CNI plugin are stored in the daemonset object, not a configmap. 
Signed-off-by: Jeremy Cowan <jicowan@hotmail.com>

Changed ConfigMap to Daemonset

---

doc_source/control-plane-logs.md

No issue.
Fix log stream name of EKS control plane log. In my environment, controller manager's (`controllerManager`) log stream starts with `kube-controller-manager-`, and scheduler's (`scheduler`) log stream starts with `kube-scheduler-`.

Fix log stream name of EKS control plane log

---

doc_source/metrics-server.md

Added an example snippet for downloading a metrics server release using curl on Linux.
This is the natural next step when following this tutorial while connected to a headless server but, there are several pitfalls as shown in this article https://echorand.me/posts/curl-download-redirect/

Example snippet for downloading metrics server

---

doc_source/retrieve-ami-id.md

Typo in parameter name in **AWS CLI** tab.
Confirmed correct value is `amazon-linux-2-gpu` from testing and other tabs.

Typo in GPU AMI parameter name

---

doc_source/update-cluster.md

When customers are upgrading EKS cluster from pre 1.13 to 1.13 or later, and if they are following the guide: "https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html", they will run into the issues where pods (aws-node, coredns etc) can't be scheduled due to the missing proper pod security policies.
Adding this note to ensure customers are aware of this potential issue. If they don't have pod security policy in place, they could follow the guide on "https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html" to create a default eks.privileged policy for backwards compatibility.
Added a note paragraph to the update-cluster page to highlight the potential issues with pod security policy admission controller …

Add Pod Security Policy Note to Upgrade Guide

---

doc_source/iam-roles-for-service-accounts-technical-overview.md

To avoid confusion, I suggest to either adding a note (as this PR), or remove PodPreset from the context.
The doc was suggesting to use PodPreset as a workaround to configure the Pod as an alternative to the Pod Identity Webhook, however, PodPreset is not yet in Beta, and not enabled on EKS yet: https://github.com/aws/containers-roadmap/issues/151

PodPreset is not yet available on EKS

---

doc_source/troubleshooting.md

If the Node is not owned by cluster, Node will fail to join the cluster. Adding this step here will help newbies.

Added one more reason to Worker Nodes Fail to Join Cluster

---

doc_source/cni-custom-network.md

Improve the document to mention a known issue after enabling ENIConfig. Refer to below discussions:
- Maximum Pods ENIConfig aware #331: https://github.com/aws/amazon-vpc-cni-k8s/issues/331
- Containers stuck in ContainerCreating after configuring CNI Custom Networking on extended CIDR #527: https://github.com/aws/amazon-vpc-cni-k8s/issues/527

Update cni-custom-network.md to mention known issue of ENIConfig

---

doc_source/load-balancing.md

As per reported issue on here: kubernetes/kubernetes#84287
Moved this doc change to Load Balancing page as per https://github.com/awsdocs/amazon-eks-user-guide/pull/63
Worker node security group requires a cluster tag so Cloud Controller Manager knows which security group to add or remove the ingress rules. Otherwise, it will cause load balancer security group failed to get removed.
If there is only one security group on the worker node, the tag is optional. The tag is only required on exactly one security group if there are multiple security groups on the worker node.
Issue #, if available:
84287
Description of changes:
Add worker node security group tagging requirement.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

Add Tagging Requirement for Worker Node Security Group

---

doc_source/getting-started-console.md

Hello, there is a section missing on tagging the public subnets so that Kubernetes can use the ALBs to create public services. It is documented [here](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) but it is missing from the getting started guide.

Add instructions to tag public subnets

---

doc_source/sec-group-reqs.md

Hi Team,
The command to show ClusterSecurityGroupId should be :
aws eks describe-cluster --name live --query cluster.resourcesVpcConfig.clusterSecurityGroupId
The command to clusterSecurityGroupId is typed as 
aws eks describe-cluster --name cluster_name --query cluster.resourcesVpcConfig.securityGroupIds
which is wrong.
Change the command to :
aws eks describe-cluster --name cluster_name --query cluster.resourcesVpcConfig.clusterSecurityGroupId

Command to show ClusterSecurityGroupId is wrong

---

doc_source/iam-roles-for-service-accounts-minimum-sdk.md

Customers are wondering if the .NET SDK supports iam roles via oidc token file
Add .NET to the list of SDKs that support it and link the release

add .NET SDK release to docs for iam role support via oidc token file

---

doc_source/eksctl.md
doc_source/getting-started-eksctl.md

Eksctl is deprecating the `latest_release` tag. To download the binary
for the latest release these Github urls should be used instead:
https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Darwin_amd64.tar.gz
https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Windows_amd64.zip

Update urls to download eksctl binaries

---

doc_source/cni-custom-network.md

There was some confusion when following the instructions for setting up
custom network configuration for multiple Availability Zones. The previous
documentation included instructions to use the `--node-labels` bootstrap
argument when creating a new worker node group, and specified the AZ
name as a node label. This doesn't work, however, when the user wants to
have a worker node group in multiple AZs. Instead, the availability zone of
the node is already added in the `failure-domain.beta.kubernetes.io/zone`
label.
We clarify these instructions by removing the `--node-labels` part of the bootstrap
args in the step which creates a worker node group and add some notes to step
5a and 5c that indicate recommended practice is to set the ENIConfig's `name`
field to that of the Availability Zone …

Clarify custom networks for multi-AZ node groups

---

doc_source/getting-started-eksctl.md

Curl command on this page was outdated for Linux installation. Changed it to match command on the home page of repository.

updated the command

---

doc_source/cni-custom-network.md

Forgot to add the "a" to signal the AZ. Thanks to @jolcese for catching this mistake!

Set ENIConfig.name to AZ correctly

---

doc_source/iam-roles-for-service-accounts-minimum-sdk.md

It was brought to my attention that there was an essential patch in a newer version than the one I initially stated. I changed the .NET version for iam roles for service accounts support accordingly in these docs.

Fix version number for .NET support of iam roles for service accounts

---

doc_source/cni-custom-network.md

Custom network configuration applies to secondary subnets added to a worker node group, not the primary subnet/ENI, which is what is specified in the Subnets field of the CloudFormation template referenced in the "Launching Amazon EKS Linux Worker Nodes" documentation.

Remove subnets from node group setup

---

doc_source/cni-env-vars.md

* Add missing variables from the AWS CNI [README.md](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/README.md)
* Moved `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG` lower in the list

Add missing environment variables

---

doc_source/migrate-stack.md

Two small changes to the `eksctl create nodegroup` command in the docs:
- Use the most recent Kubernetes version, 1.15
- Update `name` to exclude characters that fail the 'stackName' validation constraint
The `name` argument must not contain '.' otherwise it will fail validation and receive the error:
> ValidationError: 1 validation error detected: Value 'eksctl-my-cluster-nodegroup-workers-1.15' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*

Update 'eksctl create nodegroup' command in migrate-stack guide

---

doc_source/service_IAM_role.md

If you following these directions directly they will result in a EKS role that cannot setup the necessary services.  The user should select EKS Cluster and not EKS as the use case.

Updating documentation to read "EKS Cluster" instead of EKS

---

doc_source/logging-monitoring.md

We missed information about the EKS Service IAM Role in CloudWatch Authenticator Logs.
Add information about EKS Service IAM Role in CloudWatch Logs in `logging-monitoring.md` page.

Add Information about EKS Service IAM Role in CloudWatch Logs

---

doc_source/cni-env-vars.md

N/A
Updated cni-env-var doc to reflect correct log levels. Follow to https://github.com/aws/amazon-vpc-cni-k8s/pull/958

updated cni-env-var doc to reflect correct log levels

---

doc_source/update-cluster.md

its not possible for our customers to update EKS clusters up several versions. Attempts to do something like update a cluster from 1.12 to 1.14 will yield an error. Customers must step through the versions to get to latest if they are behind, and this should be documented.

Documented incremental update requirements

---

doc_source/arm-support.md

To match the latest changes in https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview
* It's called ARM, not Arm
* Default to 1.15
* Mention both A1 and M6 since they are both GA and supported in the preview

Update ARM instructions

---

doc_source/calico.md

The recommended way is to terminate the nodes.
https://github.com/aws/amazon-vpc-cni-k8s/issues/589
Suggest to restart Calico nodes to clean up added rules.

Note to users that uninstalling Calico is complex

---

doc_source/fargate-profile.md

The `eksctl` set of instructions for creating a Fargate Profile is labelled `AWS Fargate`, rather than eksctl. Contrast with, e.g., https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html, which labels it correctly.

Fix label of eksctl tab of profile-creation

---

doc_source/alb-ingress.md

This PR Avoid this error:
AccessDeniedException: User: arn:aws:sts::xxxxxxx:assumed-role/role0001/yyyyyy is not authorized to perform: wafv2:GetWebACLForResource on resource: arn:aws:wafv2:us-east-1:xxxxxx:regional/webacl
The Link for github was hard-coded to 1.14. With the new version it will miss waf2 policies.

Updated github link for iam policy.

---

doc_source/alb-ingress.md

In step 3 where it states "You can view the policy document" - it was linked to a policy for v.1.1.4 which does not have the wafv2:GetWebACLForResource permissions that are now required for alb ingress. Changed the link to point to v.1.1.8 - the same policy retrieved in the curl command below it

Update step 3 to provide link to current policy doc

---

doc_source/create-kubeconfig.md

n/a
wraps the `aws eks get-token` command in backticks

wrap get-token command in backticks

---

doc_source/load-balancing.md

There is no documentation for `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` annotation.
Here are some related issues.
* https://github.com/kubernetes/kubernetes/issues/63959
* https://github.com/kubernetes/website/pull/20906#issuecomment-647127910
I added a description of the `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` annotation.

Add aws-load-balancer-eip-allocations

---

doc_source/helm.md

Fix (replace) link to with link to replacement site artifacthub.io
Prior to this change, the previous Helm Hub link would take the browser to a 404 page.

Update link to artifacthub.io in helm.md

---

doc_source/alb-ingress.md

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1577
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1578
When upgrading from AWS ALB ingress controller to the new AWS Load Balancer controller, additional IAM policies need to be granted for controller to work properly after migration. Mention the step in the AWS documentation.

Mention additional IAM policies required for upgrade

---

doc_source/kubernetes-versions.md

no
According to [AWS Blog post](https://aws.amazon.com/fr/about-aws/whats-new/2020/10/amazon-eks-supports-kubernetes-version-1-18/) AWS release date's for EKS is October 13, 2020

[chore] AWS release date for EKS 1.18 (10/13/20)

---

doc_source/cni-upgrades.md

*Issue #, if available:*  https://github.com/aws/amazon-vpc-cni-k8s/issues/1278
Updated CNI upgrade docs to provide more context on security context changes and init container info

Update CNI upgrade docs to include security context info

---

doc_source/alb-ingress.md
doc_source/load-balancing.md

1. update docs for AWSLoadBalancerController v2.1.0 release
2. use "AWS Load Balancer Controller" instead of "AWS load balancer controller"
3. remove unnecessary sentences in the first paragraph of "Application load balancing" page.

update docs for AWSLoadBalancerController v2.1.0 release

---

doc_source/security-groups-for-pods.md

Manually editing the ds is confusing to the Cx and if the variable is not set under InitContainer then the config doesn't work. Hence providing a patch command would not be error prone.

Update command for disabling TCP_DISABLE_EARLY_DEMUX

---

doc_source/service-quotas.md

Increase default number of nodes per managed node group for EKS to 450

Increase default number of nodes per managed node group for EKS to 450

---

doc_source/load-balancing.md

Recent EKS platforms for 1.16 and later versions contain the upstream
fix "Use NLB Subnet CIDRs instead of VPC CIDRs in Health Check SG
Rules". Add a note for the changed behavior and the recommendations in
case customers hit the security group rules limit.

Add note for SG rules handling in EKS 1.16+

---

doc_source/cluster-endpoint.md

With introduction of EKS Service Linked role, which includes "route53:AssociateVPCWithHostedZone", this note is no longer required.
To avoid customers' confusion, suggest to remove this note.

Remove a Note that no longer applies

---

doc_source/efs-csi.md

The link for efs-csi-driver has been broken.
Fix broken link

Fix broken link for aws-efs-csi-driver

---

doc_source/fargate-logging.md

Ref: https://github.com/aws/containers-roadmap/issues/1197
As `kubernetes` filter plugin is not supported on Fargate yet, remove the wording to avoid misunderstanding. 

Remove the wording of kubernetes filter is supported 

---

doc_source/storage-classes.md

This is super minor, so feel free to disregard if it doesn't fit with the
general AWS style guide; but `kubectl annotate` is simpler than the
longer `kubectl patch`.
I also replaced `<gp2>` with `gp2` for consistency. (I understand that
`<>` is used in some places in the docs as a placeholder, but since
all other places in this doc use `gp2`, I thought it would avoid issues
if someone copy-pastes the command blindly.)

Suggest the simpler "annotate" command instead of a JSON patch

---

doc_source/update-cluster.md

The current command will give you a false positive, even after removing
the `upstream` line, because it's still in the yaml under `last-applied-configuration`.
Example:
Even after removing the `upstream` config option, I expect to get an
empty response, but I see this instead:
```
kubectl get configmap coredns -n kube-system -o yaml | grep upstream
{"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      upstream\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"eks.amazonaws.co …
```

Make the CoreDNS ConfigMap check more precise

---

doc_source/service-quotas.md

I can see the maximum number of Amazon ECS tasks and Amazon EKS pods running concurrently on Fargate has been updated to 1,000 as mentioned in ECS Doc [1].
I also can see the default limit for concurrent Fargate task can run per region is `10,000` via [Service Quota Console](https://console.aws.amazon.com/servicequotas/home):
But the document still say it is `500` as default limit:
Service quota | Description | Default quota value | Adjustable
-- | -- | -- | --
Fargate On-Demand resource count | The maximum number of Amazon ECS tasks and Amazon EKS pods running concurrently on Fargate in this account in the current Region. | 500 | Yes
So I am proposing the change to see if the document needs to be updated as right number of Fargate limit. …

Correct the service quota for Fargate (service-quotas.md)

---

doc_source/kubernetes-versions.md

This PR adds an FAQ regading Kubernetes feature support to https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
Also fix a typo in the same area.

add Kubernetes version support FAQ, fix a typo

---

doc_source/fargate-pod-configuration.md

This PR adds a note in https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html to make clear that Kubernetes node details are unrelated to Fargate pod size and capacity.

add pod size note in fargate-pod-configuration.md

---

doc_source/alb-ingress.md
doc_source/create-service-account-iam-policy-and-role.md
doc_source/delete-cluster.md
doc_source/update-cluster.md
doc_source/windows-support.md

This is a small set of changes tracking upstream work which allows eksctl to operate on clusters which it didn't create.
These changes remove for certain operations the note which indicates eksctl must have created the cluster. These are now supported for all EKS clusters.
This ongoing work is being tracked in https://github.com/weaveworks/eksctl/issues/2174. 

updates related to eksctl operations on non-eksctl clusters

---

doc_source/update-cluster.md

Modify the eksbuild tag suffix to `eksbuild.2` for kube-proxy v1.19.6.

Kube-proxy 1.19.6 use eksbuild.2 tag suffix

---

doc_source/load-balancing.md

The following is wrong, This will do the opposite of what is intended and is a security issue. 
The following page has the correct configuration. 
https://aws.amazon.com/premiumsupport/knowledge-center/eks-vpc-subnet-discovery/

Load balancer tagging is wrong

---

doc_source/launch-workers.md

[AMI issue](https://github.com/awslabs/amazon-eks-ami/issues/621)
The current guidance fails with a `Template format error: YAML not well-formed` because it downloads the HTML page, not the actual yaml. If we link to the GitHub raw link, it works for me.

Fixes reference to nodegroup CFN template yaml

---

doc_source/security-groups-for-pods.md

Its terminationGracePeriodSeconds not terminationGracePeriodInSeconds. See: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

Fix typo in Pod Security Groups

---

doc_source/fargate-getting-started.md

We noticed the steps provided here for the creation of a Fargate profile via AWS Console are not correct, they directly point to "To create an AWS Fargate pod execution role with the AWS Management Console", instead the steps to create the Fargate profile.
Here we can see the instruction to create the Fargate profile with eksctl, however in the tab for "AWS Management Console", the steps are for the creation of the AWS Fargate pod execution role:
--- Getting started with AWS Fargate using Amazon EKS - Create a Fargate profile for your cluster - https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-create-profile
--- https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/fargate-getting-started.md#create-a-fargate-profile-for-your-cluster …

[Discrepancy on EKS documentation] Creating a Fargate profile via AWS Console

---

doc_source/coredns.md
doc_source/update-cluster.md

[coredns.md](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/coredns.md) does not match [update-cluster.md](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/update-cluster.md) where it should. This PR updates coredns.md in alignment with https://github.com/awsdocs/amazon-eks-user-guide/pull/223

Outdated instructions in coredns.md

---

doc_source/cluster-autoscaler.md

I0220 15:27:25.416953       1 event.go:278] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-priority-expander", UID:"052af77f-725a-453a-ae2c-8873d3b3ede1", APIVersion:"v1", ResourceVersion:"827024", FieldPath:""}): type: 'Warning' reason: 'PriorityConfigMapInvalid' Wrong configmap for priority expander, doesn't contain priorities key. Ignoring update.
Cluster autoscaler fails with following error when `data.priority` property is provided for Priority Expander configMap.
```
apiVersion: v1
kind: ConfigMap
metadata:
name: cluster-autoscaler-priority-expander
namespace: kube-system
data:
priority: |-  # <<<----THIS IS BROKEN
10:
- .*eks-ng1*
50:
- .*eks-ng2*
```
- Error:
```
I0220 15:27:25.416953       1 event.go:278] …
```

updated stale config for cluster autoscaler - priority -> priorities

---

doc_source/prometheus.md

Fixing the error:
helm repo add prometheus-community https://github.com/prometheus-community/helm-charts
Error: looks like "https://github.com/prometheus-community/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/prometheus-community/helm-charts/index.yaml : 404 Not Found

Fixed Invalid Prometheus Chart

---

doc_source/cni-custom-network.md

- This pull request will add notes about `spec.securityGroups` property for ENIConfig manifest.
- When this property is not provided, aws-cni will add default security group from VPC to secondary ENI's of the worker node.

Added note for ENIConfig `spec.securityGroups` property

---

doc_source/fargate-profile.md

The embedded json for CreateFargateProfile request wasn't adding any value by including clientRequestToken and tags. These components didn't have any explanation in the following section.

Remove CreateFargateProfile json request

---

doc_source/eks-compute.md

EKS Managed nodes now supports inferentia instance types in all regions. Updating the eks-compute table to reflect this.

Update table with managed nodes inferentia support

---

doc_source/calico.md

This is a documentation PR that corresponds with the following changes:
- Switch Calico to operator: https://github.com/aws/amazon-vpc-cni-k8s/pull/1297 
- Fix Calico installation issue: https://github.com/aws/amazon-vpc-cni-k8s/pull/1410

Update documentation for Calico operator

---

doc_source/install-kubectl.md

Looking at the S3 bucket contents, version 1.18.9 is now the latest available.
N/A
Updated tools version number from 1.18.16 to 1.18.9 which is actually available for download.

Kubernetes tools v1.18.16 are no longer available

---

doc_source/managing-vpc-cni.md

This fixes a typo in the vpc-cni docs incorrectly referencing kube-proxy.

Fix typo incorrectly referencing kube-proxy

---

doc_source/create-service-account-iam-policy-and-role.md

Hello,
The Account ID variable exported at step 1 is different from the variable is used to create the trust policy (on step 3).
When running the command to generate the JSON file, the account id field is empty.
Example:

Account ID variable renamed

---

doc_source/cni-custom-network.md

The URL for the `max-pods-calculator.sh` references the GitHub repo page so the `curl` command as given downloads the HTML for the page rather than the script.
Updated the URL for `max-pods-calculator.sh` to use the raw GitHub endpoint.

Use the raw endpoint for max-pods-calculator.sh

---

doc_source/node-efa.md

*Issue #, if available:* #429
Fixing url of NCCL test job

Fix NCCL test file path for EFA on EKS

---

doc_source/efs-csi.md

serviceAccount.controller should be controller.serviceAccount
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/cc56c4c500bbf7aaea129d1f03d6ee03903e6623/charts/aws-efs-csi-driver/values.yaml#L67

fix helm to install aws-efs-csi-driver

---

doc_source/alb-ingress.md
doc_source/network-load-balancing.md

AWS load balancer controller requires exactly one sec group to be tagged with kubernetes.io/cluster/<cluster-name> when attached multiple security groups to the worker node.

mandatory security group tag

---

doc_source/fargate-logging.md

Delete labels key from sample ConfigMap

---

doc_source/eks-optimized-ami.md

There is no need to specify --kubelet-extra-args when using self managed nodes as --container-runtime by itself a independent flag [1] and should not be specified inside --kubelet-extra-args
https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L29

Flag --kubelet-extra-args not needed for containerd when using self managed nodes

---

doc_source/ebs-csi.md

This [commit](https://github.com/awsdocs/amazon-eks-user-guide/commit/db7b94af6558dcff6f60950eeb75d0001b786205#diff-e7809e03680f9563e42df4cd5c548f36f2e4265c7aa408c48b70916e5ab9d8b9) helped to solve the way values are referenced in the [values.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml) file of Helm Chart. However the commit also set ```controller.serviceAccount.create=false``` hence breaking sequence of logical steps that end user follows.
Before committing this pull request:
Steps that end user may follow:
1. Step 1A and 1B to create policy
2. Step 2, I have chosen AWS CLI method [hence no SA getting created]
3. Step 3, I have chosen Helm chart method, which currently has ```controller.serviceAccount.create=false``` hence …

Breaking change - Regression on Helm Chart values based on user preferred method of installation

---

doc_source/using-service-linked-roles-eks.md

N/A
The `AWSServiceRoleForAmazonEKS` service\-linked role trusted entity is `eks.amazonaws.com`, not `eks-fargate.amazonaws.com`

Fix trusted entity for the role

---

doc_source/cni-iam-role.md

N/A
To remove `kubectl` complaints on deprecated invocation mode and defaulted container, like:
```
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "aws-node" out of: aws-node, aws-vpc-cni-init (init)
```

Improve 'kubectl' cmd call

---

doc_source/network_reqs.md

This changes added section to https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html, that describes the steps that needs to be taken to use secondary CIDR with Amazon EKS, when the VPC is running out of IP addresses

Adding section about associating secondary CIDR and using it for node groups

---

doc_source/cni-custom-network.md

met if using a custom security group in ENIConfig
*Issue #, if available:* 350
Add a note linking https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html to ensure that the min or recommended security group settings are met when using a custom security group in the ENIConfig instead of node group security group. 

Add a note to ensure the min or recommended security group settings are

---

doc_source/ebs-csi.md

*Description of changes:* the latest example policy https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v1.3.0/docs/example-iam-policy.json has slightly more permissions: "Add permission to Create/Delete ec2:ResourceTag/kubernetes.io/cluster volumes so that CSI can Delete KCM-created volumes" https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/59a0bb134df871efd91db66ea530d943cfc83588. 

Update AWS EBS CSI driver IAM policy

---

doc_source/ebs-csi.md

*Description of changes:* These values were removed from the latest helm chart. The volume resizing and volume snapshot features are enabled by default in both install methods (helm and kustomize/yaml) so setting them isn't needed anymore as it doesn't do anything. Ref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-1.3/charts/aws-ebs-csi-driver/values.yaml
subset of https://github.com/awsdocs/amazon-eks-user-guide/pull/428

Remove obsolete enableVolumeResizing and enableVolumeSnapshot ebs csi helm values

---

doc_source/create-service-account-iam-policy-and-role.md

Updates eks cluster OIDC provider URL in IAM Role's trust relationship part.
Current example's OIDC provider url lacks `amazonaws.com`.

Update eks cluster oidc provider url

---

doc_source/aws-load-balancer-controller.md

duplicate entry exists for quay.io/jetstack/cert-manager-cainjector, while quay.io/jetstack/cert-manager-controller was missing

Update documentation aws-load-balancer-controller.md

---

doc_source/launch-workers.md

Using the current version of the shell script throws and error 
`Error: couldn't create node group filter from command line options: --name=al-nodes and argument managed=false cannot be used at the same time`
It will be confusing/frustrating for the users trying to run the command for the first time and receive such error

Update the flag managed usage in shell script

---

doc_source/fargate-logging.md

The URL for FluentBit's config file documentation changed.
*Description of changes:* This pull request replaces the broken URL for FluentBit's documentation with what I believe is the most suitable replacement. Readers who navigate to the [URL found on the existing documentation page](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file)  will encounter an error stating, "Sorry, but the page you were looking for could
not be found." The [URL I have replaced it with](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file) points to an existing documentation page that contains what appears to be identical information. (I compared the content of the page linked to by my proposed …

Fix FluentBit Config File Link

---

doc_source/aws-load-balancer-controller.md

Typo fixed "region-code.region-code" to "region-code"

Typo fixed "region-code.region-code" to "region-code"

---

doc_source/managing-vpc-cni.md

The doc currently states to use the following url to update the cni for the us-west-2 region: https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.10.1/config/master/master/aws-k8s-cni.yaml.  Which has the branch listed twice so it returns a 404.

Fix url for aws-k8s-cni.yaml

---

doc_source/restrict-service-external-ip.md

- Fix incorrect s3 link for externalip-webhook.yaml
Reference Link:
- https://docs.aws.amazon.com/eks/latest/userguide/restrict-service-external-ip.html

Fix incorrect s3 link for externalip-webhook.yaml

---

doc_source/cni-custom-network.md

The CIDR block range used in the documentation is `192.168.1.0` but was mistyped to `192.68.1.0`

fix(*): update typo for incorrect CIDR block

---

doc_source/eks-ami-versions-windows.md
doc_source/eks-optimized-windows-ami.md
doc_source/retrieve-windows-ami-id.md

Reverts awsdocs/amazon-eks-user-guide#585
We should wait until at least the August 9th end of support date.

Revert "Update Optimized AMI documentation to reflect we are no longer suppor…"

---

doc_source/platform-versions.md

Refs:
- https://aws.amazon.com/blogs/containers/amazon-eks-1-21-released/ 
- https://aws.amazon.com/blogs/containers/amazon-eks-1-20-released/ 
- https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-eks-supports-kubernetes-version-1-19/ 
- https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-kubernetes-version-1-18/
*Description of changes:*: Adds initial release dates for all major Kubernetes versions on the EKS platform versions page.
I tried to track down exact dates for each patch release as well, but couldn't find a good source. It would be nice if these were also added back for archival purposes.

Add initial release dates for all major releases

---

doc_source/windows-support.md

*Issue #, if available:* [597](https://github.com/awsdocs/amazon-eks-user-guide/issues/597)
There is a typo in the step 2 -> kubectl on macOS or Windows of the [Removing legacy Windows support from your data plane](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#remove-windows-support-data-plane).
The link in the command is malformed.
kubectl delete -f https://s3.us-west-2.amazonaws.com/amazon-eks//manifests/region-code/vpc-admission-webhook/latest/vpc-admission-webhook-deployment.yaml
Fixed the link.

Updated incorrect link as mentioned in issue #597 for removing vpc-admission-webhook

---

doc_source/security-groups-for-pods.md

https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/134
EKS just switched from service account to User for VPC resource controller. This can be a breaking change if users are using PSP to only allow SA to annotate the pod. We need to call out this change in the doc.

Update the SGP doc for PSP usage with new User authentication

---

doc_source/fargate-logging.md

Customers currently do not have any knowledge on the input config added to the fluent-bit, making this data available will help customers build better logging configuration so calling out the INPUT section of the config.

Add INPUT logging config to docs

---

doc_source/cni-metrics-helper.md

N/A
Customers were occasionally getting confused when creating an IAM role with the `eksctl` command. The most common issue was that a role with that name already existed and so the `eksctl` command did not do anything. This change adds a verification step after the role is created. It also recommends using the cluster name in the role name.

Add some notes on verifying the IAM role

---

doc_source/related-projects.md

Replace deprecated 'awesome-operators' with 'OperatorHub.io'

Replace deprecated 'awesome-operators' with 'OperatorHub.io'

---

doc_source/managing-ebs-csi.md

The previous command resulted in:
❯ kubectl descibe pvc
error: unknown command "descibe" for "kubectl"
Did you mean this?
describe
Correct command is:
~
❯ kubectl describe pvc
No resources found in default namespace.
~

Fixed the prerequisite command for ebs cni drivers

---

doc_source/install-kubectl.md

We recently updated binaries, so updating versions to reflect that and remove 1.19 since it's deprecated.

Update install kubectl instructions to the latest binaries

---

doc_source/security-groups-for-pods.md

https://github.com/awsdocs/amazon-eks-user-guide/issues/634
Clarify comment on pod to pod communication on the same node. Pods in different security groups cannot communicate because they are in different VLANs, and routing between those VLANs is disabled.

Clarify comment on pod to pod communication

---

doc_source/iam-roles-for-service-accounts-minimum-sdk.md

- This mentions that the Node v2 sdk, which is still being updated and maintained will also work with IRSA if the version is new enough.
- This adds a caveat to the .NET SDK line, since you must include the SecurityToken binary or file to make use of IRSA using .NET. More info in this [PR](https://github.com/aws-samples/one-observability-demo/pull/22) and this [PR](https://github.com/aws/aws-dotnet-extensions-configuration/pull/73/files)
It's understandable if you'd rather not include these, but this info would have helped us massively had we known it beforehand, so figured it might help others. Either way, thanks in advance for your review!
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

docs: Mention Node sdk v2 and .NET caveat

---

doc_source/connector-grant-access.md

missing word in prerequisites section
*Issue #, if available:* n/a
*Description of changes:* Add missing word in `Prerequisites` section of `connector-grant-access.md`

fix typo in connector-grant-access.md

---

doc_source/managing-kube-proxy.md

Update the Latest available kube-proxy container image version for each Amazon EKS cluster version since the information is out of date. 
v1.20.15-minimal-eksbuild.3 -> v1.20.15-minimal-eksbuild.4
v1.21.14-minimal-eksbuild.2 -> v1.21.14-minimal-eksbuild.4
v1.22.11-minimal-eksbuild.2 -> v1.22.16-minimal-eksbuild.3 

update the latest versions of managing-kube-proxy

---

doc_source/launch-workers.md

N/A
I updated the CFN template to default to 1.24, remove outdated instance types allowed values and add the NodeVolumeType field, which defaults to gp2.

Updates references to CFN template and adds NodeVolumeType field

---

doc_source/csi-iam-role.md

Remove duplicate step (**5.b** and **6**) from the EBS CSI drivers documentation

Remove duplicate step in EBS CSI driver docs

---

doc_source/cni-metrics-helper.md

Update CNI metrics helper version to v1.12.1
N/A
Now that VPC CNI v1.12.1 is released, update CNI metrics helper documentation to use v1.12.1

Update CNI metrics helper version to v1.12.1

---

doc_source/autoscaling.md

New Cluster Autoscaler versions need to have the ec2:DescribeInstanceTypes permission to allow the Pod to start with success.

Adding the missing EC2 permission

---

doc_source/install-kubectl.md

We published new binaries externally, and this updates the docs to reference the latest. We did not publish new binaries for 1.20 and below.

Updates kubectl instructions to use the latest binaries

---

doc_source/efs-csi.md

This PR is a minor fix in the efs-csi driver installation instructions with private repository mode.
No issue
The URL when running kustomize in a private repository setup is incorrect: the kustomize private setup is in the /ecr directory. This change fix the corresponding command line.

Fix efs-csi driver installation instructions

---

doc_source/managing-kube-proxy.md

Update kube-proxy v1.24.7 the correct image `v1\.24\.7\-eksbuild\.2`
Customer reported referencing the above screenshot that kube-proxy listed in *addons dropdown in console* was `v1.24.7-eksbuild.2`, while the docs mentioned in v1.24.7-eksbuild.1
We are making this consistent first.  If we want to update to mention of latest in the docs to  v1.24.9, as it is already available in the console, I will follow up with separate PR.
--- 

Update kube-proxy v1.24.7 the correct image

---

doc_source/alb-ingress.md

*Issue #, if available:* None
Previous command may fetch logs from only 1 out of all replicas for AWS Load balancer controller lead to incomplete information

Fetch load balancer controller logs from all pods

---

doc_source/fargate-logging.md

Preventing incurring CloudWatch logs charges due to unwanted Fluent Bit Process logs
To exclude shipping fluent-bit process logs to CloudWatch in an existing Amazon EKS on Fargate previously configured to push logs to CloudWatch logs. It is not enough to just restart existing workloads in the cluster for the changes in ConfigMap to take effect. 
There are no documented steps to follow to achieve this use case.

prevent pushing fluentbit process logs in existing fargate logging 

---

doc_source/install-kubectl.md

Updating the kubectl download links to latest binaries uploaded in ss3 buckets

 Updating kubectl dowload instructions to use the latest binaries

---

doc_source/managing-coredns.md

Update CoreDNS 
Testing Done
------------
```
$ aws eks describe-addon-versions --addon-name coredns --kubernetes-version 1.24 --query "addons[].addonVersions[1]"
[
{
"addonVersion": "v1.8.7-eksbuild.4",
"architecture": [
"amd64",
"arm64"
],
"compatibilities": [
{
"clusterVersion": "1.24",
"platformVersions": [
"*"
],
"defaultVersion": false
}
],
"requiresConfiguration": false
}
]
$ aws eks describe-addon-versions --addon-name coredns --kubernetes-version 1.23 --query "addons[].addonVersions[0]"
[
{
"addonVersion": "v1.8.7-eksbuild.4",
"architecture": [
"amd64",
"arm64"
],
"compatibilities": [
{
"clusterVersion": "1.23",
"platformVersions": [
"*"
],
"defaultVersion": false
}
],
"requiresConfiguration": false
}
]
$ aws eks describe-addon-versions --addon-name …
```

Update CoreDNS version to 1.8.7-eksbuild.4

---

doc_source/ebs-csi-migration-faq.md

Update formatting as the words are being merged into one so they need a space. Also removes the `No` from one of the FAQ answers because later on in the answer we say that there are no plans. So it's best to just remove the `No` because it gives the impression that there it will never be removed, whereas the `No plans to remove them` doesn't remove that option completely, it just says there are no plans currently (which could change)

fix: formatting and removes ambiguity in answer

---

doc_source/calico.md

https://github.com/aws/amazon-vpc-cni-k8s/issues/2287
This PR removes sections related to installing Calico from manifests present in VPC CNI repository. These manifests are being removed and helm from upstream is the only recommended installation method.

Remove calico manifest installation sections

---

doc_source/managing-vpc-cni.md

N/A
This PR updates the VPC CNI recommended version to v1.12.5-eksbuild.2. It also cleans up the example versions a bit.

Update VPC CNI recommended version

---

doc_source/efs-csi.md

n/a but a little bit confusing due to example files provided using different naming convention
As per https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/1f49c2f73b71614f5e0e157a0420f9378ce42615/examples/kubernetes/dynamic_provisioning/specs/pod.yaml#L17 the new name of the pod is efs-app

EFS example output incorrect name compared to the naming given in the example files

---

doc_source/csi-iam-role.md

IAM policy expects an ARN for the resource property. Key ID changed to Key ARN in the documentation.

KMS key ID changed to ARN for the IAM Policy

---

doc_source/eks-optimized-windows-ami.md

1. Add section about cached images for all supported EKS versions.
2. Added information about both runtime i.e. docker and containerd.

Add information about cached container images on EKS Windows AMIs

---

doc_source/kubernetes-versions.md

Adding end of support date for Kubernetes v1.23
Added end of support date for Kubernetes v1.23 on EKS. Earlier it was just month and year, now added an accurate date

Added date for Kubernetes v1.23 EOS

---

doc_source/cost-monitoring.md

Kubecost version `1.96` is broken and Pod cannot pass ReadinessProbe health check when running on Kubernetes `1.25` due to it uses Beta API version (`autoscaling/v2beta`) with the following error in the cost analyzer log:
```
$ kubectl get pods -n kubecost
NAME                                           READY   STATUS    RESTARTS   AGE
kubecost-cost-analyzer-78f8c76f76-wqr2x        0/2     Running   0          33s
kubecost-kube-state-metrics-75df9fd84f-bkjx8   1/1     Running   0          169m
kubecost-prometheus-server-fd44c55d4-vstkd     1/1     Running   0          169m
```
```
E0323 15:30:56.113107       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v2beta1.HorizontalPodAutoscaler: failed to list …
```

Update kubecost for supporting k8s 1.25

---

doc_source/cni-network-policy.md

The command to edit the `aws-node` daemonset was wrong, so I updated it.

Fix command to edit aws-node for CNI network policy doc

---

doc_source/install-aws-iam-authenticator.md

Latest release of aws-iam-authenticator tool is 0.6.11, see link below https://github.com/kubernetes-sigs/aws-iam-authenticator/releases

Update aws-iam-authenticator version from 0.5.9 to 0.6.11

---

doc_source/update-cluster.md

*Issue #740 
The `Pod Security Policies` feature has been removed since the version `1.25` as per indicated under [the Kubernetes documentation](https://kubernetes.io/docs/concepts/security/pod-security-policy/).

Update update-cluster with the latest status of PSP

---

doc_source/managed-node-groups.md

*Description of changes:* on the Managed Node Groups page there is a list of VPC endpoints that users must create if they want to use Private Subnets. It seems like there is a mistake in the S3 endpoint.

fix: s3 gateway endpoint

---

doc_source/cni-custom-network.md

Broken Link > "https://docs.aws.amazon.com/vpc/latest/userguide/create-vpc.html#add-ipv4-cidr" 
Broken Link need to replaced "https://docs.aws.amazon.com/vpc/latest/userguide/create-vpc.html#add-ipv4-cidr" 
with https://docs.aws.amazon.com/vpc/latest/userguide/modify-vpcs.html#add-ipv4-cidr

Update cni-custom-network.md with broken Link to VPC Configuration Doc

---

doc_source/pod-id-role.md

Fix action taken - EKS Pod Identity uses `AssumeRole` to assume the IAM role, not 'TagSession'.

Update pod-id-role.md - fix action taken in doc

---

doc_source/coredns-autoscaling.md

`minReplicas` and `maxReplicas` need to go inside the `autoScaling` block.
Current documented command returns:
```
An error occurred (InvalidParameterException) when calling the UpdateAddon operation: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.minReplicas: is not defined in the schema and the schema does not allow additional properties, $.maxReplicas: is not defined in the schema and the schema does not allow additional properties]
```

Correct configuration values for updating CoreDNS auto-scaling via CLI

---

doc_source/eks-add-ons.md
doc_source/managing-kube-proxy.md

- The different versions between kube-proxy and kubelt are allowed.
- It's unnecessary updating kubelet before kube-proxy.
cf.
- https://github.com/kubernetes/website/pull/40932
- https://kubernetes.io/releases/version-skew-policy/#kube-proxy

Update eks-add-ons.md/managing-kube-proxy.md about kube-proxy version skew policy

---

doc_source/install-kubectl.md

Download link for Kubernetes 1.30 is duplicated both for `Linux (amd64)` and `Linux (arm64)`. This PR removes duplication.

Removed duplicated entries of 1.30 for linux

---

doc_source/authenticate-oidc-identity-provider.md

Fixed a typo in the documentation.

Fix typo in authenticate-oidc-identity-provider.md

---

doc_source/s3-csi.md

Starting from `v1.8.0`, Mountpoint for Amazon S3 CSI Driver added support for configuring tolerations. This PR shows possible configuration values and how to apply them.
/cc @dannycjones @muddyfish

Mention toleration configuration for Mountpoint for Amazon S3 CSI Driver

---

doc_source/update-managed-node-group.md

Added further details as discussed with internal team regarding PDBs not being considered during an EKS MNG scalingConfig modification. Multiple customers were confused on the fact that EKS MNG do not consider PDBs, so added the **Important** section at the bottom to clarify that changing the scalingConfig of an EKS MNG does not follow the same workflow as updating an EKS MNG.

Added PDB details to 'Edit a nodegroup' section

---

doc_source/kubernetes-versions.md

EKS v1.23 reached end of extended support on Oct 11th, 2024, but AWS EKS Documentation still shows EKS v1.23 under available versions in Extended support. So removed it to avoid confusion.

Removed v1.23 from currently available in extended support

---

doc_source/disable-extended-support.md
doc_source/enable-extended-support.md

*Issue #, if available:* Using the `aws eks update-cluster-config` command provided in disable-extended-support and enable-extended-support documentation caused below error:
>> Unknown options: STANDARD, =
*Description of changes:* The error was because the command to enable/disable Extended support had `supportType = string` where the additional spaces before and after "=" was causing issue. So changed it to `supportType=string` which follows the correct shorthand Syntax. 

Nambinayagan patch 1
